export interface IServiceOrderDetails {
	desformapag: string;
	TipoCompromiso: string;
	NumeroCompromiso: string;
	CodigoInterno: string | null;
	CompaniaCodigo: string;
	UnidadNegocio: string;
	Proveedor: number;
	MonedaDocumento: string;
	MonedaPago: string;
	TipoPago: string;
	FormadePago: string;
	FechaEntrega: string;
	FechaDocumento: string;
	DiasparaPago: number;
	TipodeServicio: string;
	TipodeServiciocxp: string;
	TipodeCotizacion: string;
	MontoNoAfecto: number;
	MontoAfecto: number;
	MontoCompromisoOriginal: number;
	MontoCompromiso: number;
	MontoImpuesto: number;
	MontoGastado: number;
	ProvisionTipoFlag: string | null;
	FechaPreparacion: string;
	FechaAprobacion: string;
	PreparadaPor: number;
	AprobadaPor: number;
	EstadoCompromiso: string;
	ImpresionNumero: number;
	ContraPrestacionFlag: string;
	CPPendienteFlag: string;
	Periodicidad: string | null;
	PeriodoAplicacion: string | null;
	PrecioUnitario: number;
	Comentarios: string | null;
	UltimaFechaModif: string;
	UltimoUsuario: string;
	Descripcion: string;
	Busqueda: string;
	RazonRechazo: string | null;
	Observaciones: string;
	NumeroContrato: string | null;
	FechaEnvioProveedor: string | null;
	Clasificacion: string;
	DescripcionLocal: string;
	NivelAprobacion: string;
}